# Generated by Django 5.2 on 2025-12-20 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Quote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.TextField(help_text="The inspirational quote")),
                (
                    "author",
                    models.CharField(help_text="Author or source", max_length=200),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("integrity", "Integrity"),
                            ("responsibility", "Responsibility"),
                            ("trust", "Trust"),
                            ("respect", "Respect"),
                            ("harmony", "Harmony"),
                            ("general", "General"),
                        ],
                        default="general",
                        max_length=100,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
