# Generated by Django 5.2 on 2025-12-20 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Activity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("date", models.DateField()),
                ("value_practiced", models.CharField(max_length=100)),
                (
                    "student_count",
                    models.PositiveIntegerField(
                        help_text="Number of students involved"
                    ),
                ),
                ("description", models.TextField(blank=True)),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="activities/"),
                ),
            ],
            options={
                "verbose_name_plural": "Activities",
            },
        ),
    ]
