# Generated by Django 5.2 on 2025-12-20 09:49

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ReflectionScenario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("scenario_text", models.TextField()),
                (
                    "explanation",
                    models.TextField(
                        help_text="Reflective explanation shown after selection"
                    ),
                ),
                (
                    "related_value",
                    models.CharField(default="Responsibility", max_length=100),
                ),
                (
                    "active_date",
                    models.DateField(
                        default=django.utils.timezone.now,
                        help_text="Date this scenario is active",
                        unique=True,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ReflectionOption",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("option_text", models.CharField(max_length=300)),
                (
                    "scenario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="options",
                        to="reflections.reflectionscenario",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="UserResponse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "scenario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="reflections.reflectionscenario",
                    ),
                ),
                (
                    "selected_option",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="reflections.reflectionoption",
                    ),
                ),
            ],
        ),
    ]
