# Generated by Django 4.2.28 on 2026-03-07 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("voices", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="studentvoice",
            options={
                "verbose_name": "Impact Story",
                "verbose_name_plural": "Impact Stories",
            },
        ),
        migrations.AlterField(
            model_name="studentvoice",
            name="content",
            field=models.TextField(help_text="Short story of change (100-150 words)"),
        ),
    ]
