# Generated by Django 4.2.28 on 2026-03-07 10:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("voices", "0002_alter_studentvoice_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="StoryMedia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        help_text="Upload photo or video", upload_to="story_media/"
                    ),
                ),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "story",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="media",
                        to="voices.studentvoice",
                    ),
                ),
            ],
        ),
    ]
