# Generated by Django 4.2.28 on 2026-03-18 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("voices", "0003_storymedia"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="studentvoice",
            options={
                "ordering": ["order", "-created_at"],
                "verbose_name": "Impact Story",
                "verbose_name_plural": "Impact Stories",
            },
        ),
        migrations.AddField(
            model_name="studentvoice",
            name="order",
            field=models.PositiveIntegerField(default=100),
        ),
    ]
