# Generated by Django 5.1.4 on 2026-01-15 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Innovation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("slug", models.SlugField(blank=True, unique=True)),
                (
                    "description",
                    models.TextField(
                        help_text="Detailed information about the project"
                    ),
                ),
                (
                    "short_description",
                    models.CharField(
                        help_text="A brief summary for the thumbnail", max_length=250
                    ),
                ),
                ("thumbnail", models.ImageField(upload_to="innovations/thumbnails/")),
                (
                    "innovation_type",
                    models.CharField(
                        choices=[
                            ("app", "Mobile Application"),
                            ("website", "Website/Portal"),
                            ("tool", "Digital Tool"),
                            ("research", "Research Project"),
                        ],
                        default="website",
                        max_length=20,
                    ),
                ),
                (
                    "developed_by",
                    models.CharField(
                        help_text="Names of students/faculty involved", max_length=300
                    ),
                ),
                (
                    "link",
                    models.URLField(help_text="Direct link to the project/website"),
                ),
                ("is_featured", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "UHV Innovation",
                "verbose_name_plural": "UHV Innovations",
                "ordering": ["-is_featured", "-created_at"],
            },
        ),
    ]
