# Generated by Django 5.2 on 2025-12-20 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Resource",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=300)),
                ("description", models.TextField()),
                (
                    "resource_type",
                    models.CharField(
                        choices=[
                            ("article", "Article"),
                            ("video", "Video"),
                            ("pdf", "PDF Document"),
                            ("link", "External Link"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "url",
                    models.URLField(
                        blank=True, help_text="External link or video URL", null=True
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        blank=True,
                        help_text="Upload PDF or document",
                        null=True,
                        upload_to="resources/",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("integrity", "Integrity"),
                            ("responsibility", "Responsibility"),
                            ("trust", "Trust"),
                            ("respect", "Respect"),
                            ("harmony", "Harmony"),
                            ("general", "General"),
                        ],
                        default="general",
                        max_length=100,
                    ),
                ),
                (
                    "thumbnail",
                    models.ImageField(
                        blank=True, null=True, upload_to="resource_thumbnails/"
                    ),
                ),
                ("is_featured", models.BooleanField(default=False)),
                ("views_count", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-is_featured", "-created_at"],
            },
        ),
    ]
