# Generated by Django 4.2.28 on 2026-03-06 19:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CoreValue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField()),
                (
                    "icon",
                    models.CharField(
                        default="🤝", help_text="Emoji or Icon code", max_length=10
                    ),
                ),
                ("order", models.IntegerField(default=0)),
            ],
            options={
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="NewsUpdate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.CharField(max_length=255)),
                (
                    "icon_type",
                    models.CharField(
                        choices=[
                            ("update", "Update Icon (Circle)"),
                            ("event", "Event Icon (Calendar)"),
                            ("voice", "Voice Icon (Speaker)"),
                            ("heart", "Heart Icon"),
                        ],
                        default="update",
                        max_length=20,
                    ),
                ),
                (
                    "link",
                    models.CharField(
                        blank=True, help_text="Optional URL to link to", max_length=255
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("order", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["order", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ValueExample",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "level",
                    models.CharField(
                        choices=[
                            ("Family", "Family"),
                            ("College", "College"),
                            ("Society", "Society"),
                            ("Profession", "Profession"),
                        ],
                        max_length=50,
                    ),
                ),
                ("text", models.TextField()),
                (
                    "core_value",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="examples",
                        to="core.corevalue",
                    ),
                ),
            ],
        ),
    ]
