# Generated by Django 4.2.28 on 2026-03-11 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_contactmessage"),
    ]

    operations = [
        migrations.CreateModel(
            name="SiteVisitor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ip_address", models.GenericIPAddressField(unique=True)),
                ("last_visit", models.DateTimeField(auto_now=True)),
                ("visit_count", models.PositiveIntegerField(default=1)),
            ],
        ),
    ]
