# Generated by Django 5.2 on 2025-12-20 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("journals", "0002_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="journalentry",
            options={
                "ordering": ["-created_at"],
                "verbose_name_plural": "Journal Entries",
            },
        ),
        migrations.AddField(
            model_name="journalentry",
            name="mood",
            field=models.CharField(
                blank=True,
                choices=[
                    ("happy", "😊 Happy"),
                    ("calm", "😌 Calm"),
                    ("thoughtful", "🤔 Thoughtful"),
                    ("grateful", "🙏 Grateful"),
                    ("challenged", "💪 Challenged"),
                    ("confused", "😕 Confused"),
                ],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="journalentry",
            name="tags",
            field=models.CharField(
                blank=True, help_text="Comma-separated tags", max_length=200
            ),
        ),
        migrations.AddField(
            model_name="journalentry",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
